import Head from 'next/head'
import Image from 'next/image'
import { Inter,Open_Sans } from 'next/font/google'
import Sidebar from '@/components/NavBars/Sidebar'
import {AiOutlineDownload} from "react-icons/ai"
import PiezoListTable from '@/components/MonitoringMap/PiezoListTable'
import PiezoFilterComp from '@/components/MonitoringMap/MapFiltering/PiezoFilterComp'
import Map from '@/components/MonitoringMap/Map'
import StateShowing from '@/components/MonitoringMap/StateShowing'
import { BsBookmarkHeartFill, BsPlusSquare } from 'react-icons/bs'


const inter = Inter({ subsets: ['latin'] })
const openSans = Open_Sans({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rossing Uranium | Remote sensing app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${openSans.className} flex md:pl-20 lg:pl-24 2xl:pl-28`} >
        <Sidebar/>

        <div className=' px-4 py-12 md:px-8  lg:p-12  2xl:p-16 w-full'>
          <div className='flex items-center justify-between gap-x-8 gap-y-8 flex-wrap'>

            <h1 className=' md:text-lg 2xl:text-xl font-bold'>Monitoring Map (92 Piezometers)</h1>
            <button className='flex items-center gap-x-2 md:gap-x-3 lg:gap-x-4 px-4 py-2 bg-[#222] text-white rounded-xl'>
              <AiOutlineDownload className='w-4 h-4 md:w-5 md:h-5 lg:w-6 lg:h-6 '/>
              <span className='text-sm md:text-base lg:text-lg'>Generate report</span>
            </button>
          </div>

          <div className='md:bg-[#ddd] bg-white   md:px-8 md:py-10  rounded-2xl mt-12 flex flex-col gap-y-12'>

            
              <h2 className='font-semibold flex gap-x-12 items-end'>
                <span className='md:text-lg 2xl:text-xl'>Proposed piezometers</span>
                <span className='text-2xl lg:text-3xl 2xl:text-4xl text-[#7B8831]'>12</span>
              </h2>

              

            

            <div className='grid grid-cols-1 lg:grid-cols-2 gap-x-8 xl:gap-x-10 gap-y-8 xl:gap-y-10'>

              <PiezoListTable/>

              <PiezoFilterComp/>
            </div>
            
            <StateShowing/>

            <Map/>

          </div>
        </div>
        
      </main>
    </>
  )
}
