import Head from 'next/head'
import Image from 'next/image'
import { Inter,Open_Sans } from 'next/font/google'
import Sidebar from '@/components/NavBars/Sidebar'
import {AiOutlineDownload} from "react-icons/ai"
import PiezoListTable from '@/components/MonitoringMap/PiezoListTable'
import PiezoFilterComp from '@/components/MonitoringMap/MapFiltering/PiezoFilterComp'
import Map from '@/components/MonitoringMap/Map'
import StateShowing from '@/components/MonitoringMap/StateShowing'
import LecturesLocationTable from '@/components/PiezometerLectures/LecturesLocationTable'



const openSans = Open_Sans({ subsets: ['latin'] })

export default function PiezometerLectures() {
  return (
    <>
      <Head>
        <title>Rossing Uranium | Remote sensing app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${openSans.className} flex`} >
        <Sidebar/>

        <div className='md:ml-20 lg:ml-24 2xl:ml-28 px-4 py-12 md:px-8  lg:p-12  2xl:p-16 w-full'>
          <div className='flex flex-col gap-y-12 '>

            <h1 className=' md:text-lg 2xl:text-xl font-bold'>Piezometer Lectures</h1>
            
            <p className='text-xs xl:text-sm'>Use the interactive chart below to explore piezometer readings from paddock</p>
          </div>

          <div className='md:bg-[#ddd] bg-white   md:px-8 md:py-10  rounded-2xl mt-12 flex flex-col gap-y-12'>

            <LecturesLocationTable/>

            <div className='grid grid-cols-1 lg:grid-cols-2 gap-x-8 xl:gap-x-10 gap-y-8 xl:gap-y-10'>

              <PiezoListTable/>

              <PiezoFilterComp/>
            </div>
            
            <StateShowing/>

            <Map/>

          </div>
        </div>
        
      </main>
    </>
  )
}