import Sidebar from '@/components/NavBars/Sidebar'
import SliderComp from '@/components/Slider/SliderComp'
import { Open_Sans } from 'next/font/google'
import Head from 'next/head'
import React from 'react'
import {BsBookmarkHeartFill, BsChevronLeft,BsChevronRight, BsPlusSquare} from "react-icons/bs"

const openSans = Open_Sans({ subsets: ['latin'] })

function Slider() {
  return (
    <>
      <Head>
        <title>Rossing Uranium | Remote sensing app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${openSans.className} `} >
        
        <Sidebar/>

        <div className='md:ml-20 lg:ml-24 2xl:ml-28 px-4 py-12 md:px-8  lg:p-12  2xl:p-16  '>
          
          <div className='items-center flex flex-wrap justify-between'>

            <h1 className=' md:text-lg 2xl:text-xl font-bold'>Slider</h1>

            <div className='flex items-center gap-x-4'>
                <div className='w-8 h-8 bg-[#333] flex items-center justify-center rounded-full text-white '>
                  <BsBookmarkHeartFill className='w-3 h-3'/>
                </div>

                <button className='flex items-center gap-x-2 px-3 py-2 bg-[#333] text-white rounded-[8px]'>
                  <BsPlusSquare className='w-3 h-3'/>
                  <span className='text-xs font-bold'>new</span>
                </button>
            </div>

          </div>
            
          <div className='grid-cols-1 lg:grid-cols-2 grid gap-x-10 gap-y-10 mt-10 md:mt-0'>

            <div className='md:bg-[#ddd] bg-white   md:p-6   rounded-2xl  flex flex-col  gap-y-4 w-full '>

              <h2 className='font-semibold md:text-lg 2xl:text-xl'>
                Latest reports  
              </h2>

              <div className='w-full '>
                <SliderComp/>
              </div>
            </div>


            <div className='md:bg-[#ddd] bg-white   md:p-6   rounded-2xl  flex flex-col  gap-y-4 w-full '>

            <h2 className='font-semibold md:text-lg 2xl:text-xl'>
                Mi marked reports 
              </h2>

              <div className='w-full '>
                <SliderComp/>
              </div>
            </div>


            
          </div>

          
        </div>
        
      </div>
    </>
  )
}

export default Slider